# Generated by Django 5.2.1 on 2025-05-26 05:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tematica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Guia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programa', models.CharField(max_length=100)),
                ('semana', models.IntegerField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('Borrador', 'Borrador'), ('Publicada', 'Publicada')], default='Borrador', max_length=20)),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guias', to=settings.AUTH_USER_MODEL)),
                ('tematica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='guia.tematica')),
            ],
        ),
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('url', models.URLField()),
                ('guia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recursos', to='guia.guia')),
            ],
        ),
    ]
